CREATE
	TYPE STATUS AS ENUM ('ACTIVE', 'INACTIVE');

CREATE TABLE FUB_TAXI
(
	UUID       UUID        NOT NULL PRIMARY KEY,
	LAT        DECIMAL     NOT NULL,
	LONG       DECIMAL     NOT NULL,
	COLOR      VARCHAR(30) NOT NULL,
	AVG_SPEED  DECIMAL     NOT NULL,
	IS_ENGAGED BOOLEAN     NOT NULL,
	STATUS     STATUS      NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE FUB_USER
(
	UUID         UUID        NOT NULL PRIMARY KEY,
	NAME         VARCHAR(30) NOT NULL,
	PHONE_NUMBER VARCHAR(30) NOT NULL,
	STATUS       STATUS      NOT NULL DEFAULT 'ACTIVE'
);