CREATE
	TYPE STATUS AS ENUM ('ACTIVE', 'INACTIVE');
CREATE
	TYPE TAXI_TYPE AS ENUM ('PINK', 'ALL');

CREATE TABLE FUB_TAXI
(
	UUID       UUID      NOT NULL PRIMARY KEY,
	LAT        DECIMAL   NOT NULL,
	LONG       DECIMAL   NOT NULL,
	TAXI_TYPE  TAXI_TYPE NOT NULL,
	AVG_SPEED  DECIMAL   NOT NULL,
	IS_ENGAGED BOOLEAN   NOT NULL,
	STATUS     STATUS    NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE FUB_USER
(
	UUID         UUID        NOT NULL PRIMARY KEY,
	NAME         VARCHAR(30) NOT NULL,
	PHONE_NUMBER VARCHAR(30) NOT NULL,
	STATUS       STATUS      NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE FUB_RIDE
(
	UUID       UUID    NOT NULL PRIMARY KEY,
	USER_ID    UUID    NOT NULL,
	TAXI_ID    UUID    NOT NULL,
	ORIG_LAT   DECIMAL NOT NULL,
	ORIG_LONG  DECIMAL NOT NULL,
	DEST_LAT   DECIMAL NOT NULL,
	DEST_LONG  DECIMAL NOT NULL,
	AMOUNT     DECIMAL,
	RIDE_START TIMESTAMP,
	RIDE_END   TIMESTAMP,
	STATUS     STATUS      NOT NULL DEFAULT 'ACTIVE'
);